version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0
  # heroku: circleci/heroku@1.2.6

jobs:
  build:
    working_directory: ~/psydiary_back_end # THIS SHOULD BE NAME OF YOUR APP
    docker:
      - image: cimg/ruby:3.1.1
        environment:
          PGHOST: localhost
          PGUSER: psydiary_back_end # THIS SHOULD BE NAME OF YOUR APP
          RAILS_ENV: test
          ipgeo_api_key: ENV['ipgeo_api_key']
      - image: postgres:13.2
        environment:
          POSTGRES_USER: psydiary_back_end # THIS SHOULD BE NAME OF YOUR APP
          POSTGRES_DB: psydiary_back_end_test # find db name in /config/database.yml
          POSTGRES_PASSWORD:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: psydiary_back_end # THIS SHOULD BE NAME OF YOUR APP
          command: bundle -v
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
#   deploy: # this can be any name you choose
#     executor: heroku/default
#     steps:
#       - attach_workspace:
#           at: ~/psydiary_back_end
#       - heroku/deploy-via-git:
#           force: true
# workflows:
#   test_my_app:
#     jobs:
#       - build_and_test
#       - deploy:
#           requires:
#             - build_and_test # only deploy if the build_and_test job has completed
#           filters:
#             branches:
#               only: main # only deploy when on main